# fly.toml app configuration file generated for generator-long-tree-8710 on 2024-10-01T10:03:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'generator-long-tree-8710'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
