PUT   http://localhost:3001/partners/66f57039d4679a330e15fa06
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjQ3ZTVjMTk2YTUxMzJlNWFiOGE4MCIsImlhdCI6MTcyNzM1ODkzMX0.52iIbthW601vTP2u78X_TEmlX5hQtuOOIZn0f6x6RYo

{
    "serviceType" : "movers",
    "contactInfo" : {
        "phone" : "345873234",
        "email" : "mover@gamail.com",
        "contactAddress" : "mitheru"
    }

}